### ISSUE TITLE
log spoiled with org.xml.sax.SAXException: Done

### ISSUE THREAD

**Issue by cdietrich** [eclipse-emf/org.eclipse.emf#2]
in our Xtext dev IDE the log is spammed with following exception
it would be nice to also log the offending plugin.xml file
```
org.xml.sax.SAXException: Done
	at org.eclipse.emf.ecore.plugin.EcorePlugin$1Handler.startElement(EcorePlugin.java:383)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3079)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at org.eclipse.emf.ecore.plugin.EcorePlugin.computePlatformPluginToPlatformResourceMap(EcorePlugin.java:460)
	at org.eclipse.emf.ecore.plugin.EcorePlugin.computePlatformURIMap(EcorePlugin.java:571)
	at org.eclipse.xtext.ui.resource.JavaProjectResourceSetInitializer.computePlatformURIMap(JavaProjectResourceSetInitializer.java:62)
	at org.eclipse.xtext.ui.resource.JavaProjectResourceSetInitializer.initialize(JavaProjectResourceSetInitializer.java:51)
	at org.eclipse.xtext.ui.resource.XtextResourceSetProvider.get(XtextResourceSetProvider.java:54)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:518)
	at org.eclipse.xtext.builder.impl.XtextBuilder.addInfosFromTaskAndBuild(XtextBuilder.java:455)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:436)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:339)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:196)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:289)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

in this case remote debugging revealed https://github.com/eclipse/xtext/issues/2189 as cause
but the question is what is bad. aint it normal there is no pluginId?

no it seems to be logged for all plugin.xml

**Comment by cdietrich** [comment]
saxexception("done")
produded at

```
EcorePlugin$1Handler.startElement(String, String, String, Attributes) line: 383	
SAXParserImpl$JAXPSAXParser(AbstractSAXParser).startElement(QName, XMLAttributes, Augmentations) line: 518	
XMLNSDocumentScannerImpl.scanStartElement() line: 374	
XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook() line: 613	
XMLNSDocumentScannerImpl$NSContentDriver(XMLDocumentFragmentScannerImpl$FragmentContentDriver).next() line: 3079	
XMLDocumentScannerImpl$PrologDriver.next() line: 836	
XMLNSDocumentScannerImpl(XMLDocumentScannerImpl).next() line: 605	
XMLNSDocumentScannerImpl.next() line: 112	
XMLNSDocumentScannerImpl(XMLDocumentFragmentScannerImpl).scanDocument(boolean) line: 542	
XIncludeAwareParserConfiguration(XML11Configuration).parse(boolean) line: 889	
XIncludeAwareParserConfiguration(XML11Configuration).parse(XMLInputSource) line: 825	
SAXParserImpl$JAXPSAXParser(XMLParser).parse(XMLInputSource) line: 141	
SAXParserImpl$JAXPSAXParser(AbstractSAXParser).parse(InputSource) line: 1224	
SAXParserImpl$JAXPSAXParser.parse(InputSource) line: 637	
SAXParserImpl.parse(InputSource, DefaultHandler) line: 326	
EcorePlugin.computePlatformPluginToPlatformResourceMap() line: 460	
```

**Comment by cdietrich** [comment]
we have a project that has a plugin.xml with no id and  no manifest

**Comment by cdietrich** [comment]
potential workaround
```
<plugin
   id="org.eclipse.xtext.common.types.tests"
>
```

**Comment by merks** [comment]
Is it a "broken" project?  Of course we expect every bundle to have an ID...

**Comment by cdietrich** [comment]
it is cause this is not a plugin project. the question is why it has the plugin.xml
need to find out with @lorenzobettini

**Comment by LorenzoBettini** [comment]
As I said in our bug: Yes: that is a JAR packaging type project, with no PDE nature, whose tests are meant to be executed with maven surefire, NOT with tycho surefire, so the missing MANIFEST is intentional. I can't say anything about the plugin.xml file because it's always been there, and I left it as it is.

**Comment by merks** [comment]
FYI, I just ripped the support for processing the plugin.xml.  Surely no one in the world has such pre-OSGi bundles anymore.
